# =============================================================================
# Verify Appendix Tables - Check that all required tables exist
# =============================================================================
# This script verifies that all tables referenced in the appendix have been
# generated by the R analysis pipeline.
# =============================================================================

cat("\n=============================================================================\n")
cat("VERIFYING APPENDIX TABLES\n")
cat("=============================================================================\n\n")

# Define output directories. Run this script from the repository root after
# R/main_analysis.R has generated the writing_draft outputs.
tables_dir <- file.path(getwd(), "writing_draft", "tables")
cache_dir <- file.path(getwd(), "data", "cache")

# Define all tables that SHOULD be generated by R code
required_tables <- list(

  # Balance and Randomization Checks (from balance_and_checks.R)
  balance = c(
    "attention_check_summary.tex",
    "attention_check_summary.csv",
    "attention_check_by_treatment.csv",
    "balance_wald_table.tex",
    "balance_tests_table.tex",
    "balance_tests_individual.csv",
    "attrition_tests_table.tex"
  ),

  # Cached permutation results used by balance_and_checks_quick.R
  permutation_cache = c(
    "balance_wald_test.csv",
    "attrition_tests.csv"
  ),

  # Sensitivity Analysis (from modeling_sensitivity.R)
  sensitivity = c(
    "sensitivity_pooled_table.tex",
    "sensitivity_recontact_table.tex"
  ),

  # Main Model Tables (from modeling.R)
  models = c(
    "main_models.tex",
    "Human_in_the_Loop_models.tex",
    "party_models.tex",
    "rumor_models.tex",
    "Other_Election_Integrity_models.tex",
    "cisa_models_table.tex",
    "cisa_models_table_unweighted.tex"
  ),

  # Summary Statistics (from tables.R)
  summary_stats = c(
    "summary_statistics_all.tex",
    "summary_statistics_age_group.tex",
    "summary_statistics_education_level.tex",
    "summary_statistics_gender.tex",
    "summary_statistics_ideology.tex",
    "summary_statistics_party_identification.tex",
    "summary_statistics_political_interest.tex",
    "summary_statistics_race_ethnicity.tex",
    "summary_statistics_urban_rural.tex",
    "summary_statistics_region.tex"
  ),

  # Cross-wave Summary Statistics (from tables.R)
  cross_wave = c(
    "cross_wave_factor_summary_statistics_age_group.tex",
    "cross_wave_factor_summary_statistics_education_level.tex",
    "cross_wave_factor_summary_statistics_gender.tex",
    "cross_wave_factor_summary_statistics_ideology.tex",
    "cross_wave_factor_summary_statistics_party_identification.tex",
    "cross_wave_factor_summary_statistics_political_interest.tex",
    "cross_wave_factor_summary_statistics_race_ethnicity.tex",
    "cross_wave_factor_summary_statistics_urban_rural.tex"
  )
)

# Check each category
all_tables_exist <- TRUE
missing_tables <- list()

for (category in names(required_tables)) {
  cat(sprintf("\nChecking %s tables:\n", category))
  category_tables <- required_tables[[category]]
  category_dir <- if (identical(category, "permutation_cache")) cache_dir else tables_dir

  for (table_file in category_tables) {
    table_path <- file.path(category_dir, table_file)
    if (file.exists(table_path)) {
      cat(sprintf("  ✓ %s\n", table_file))
    } else {
      cat(sprintf("  ✗ MISSING: %s\n", table_file))
      all_tables_exist <- FALSE
      missing_tables[[category]] <- c(missing_tables[[category]], table_file)
    }
  }
}

# Summary
cat("\n=============================================================================\n")
if (all_tables_exist) {
  cat("SUCCESS: All required tables exist!\n")
  cat("=============================================================================\n")
} else {
  cat("WARNING: Some tables are missing!\n")
  cat("=============================================================================\n\n")
  cat("Missing tables by category:\n")
  for (category in names(missing_tables)) {
    cat(sprintf("\n%s:\n", category))
    for (table in missing_tables[[category]]) {
      cat(sprintf("  - %s\n", table))
    }
  }
  cat("\nRun the appropriate R scripts to generate these tables:\n")
  cat("  - balance_and_checks.R for balance/attrition tables\n")
  cat("  - modeling_sensitivity.R for sensitivity analysis tables\n")
  cat("  - modeling.R for main model tables\n")
  cat("  - tables.R for summary statistics\n")
}

# Also check for any .tex files in data directory that are NOT in our list
cat("\n=============================================================================\n")
cat("Checking for unexpected .tex files in data directory...\n")
cat("=============================================================================\n\n")

all_tex_files <- list.files(tables_dir, pattern = "\\.tex$", full.names = FALSE)
expected_files <- unlist(required_tables)
expected_files <- expected_files[grepl("\\.tex$", expected_files)]

unexpected_files <- setdiff(all_tex_files, expected_files)
cat(sprintf("Found %d additional generated .tex files outside the minimal checklist.\n", length(unexpected_files)))
cat("These are not treated as errors; many are intermediate appendix/model tables.\n")

cat("\n")
