# =============================================================================
# Verify Appendix Tables - Check that all required tables exist
# =============================================================================
# This script verifies that all tables referenced in the appendix have been
# generated by the R analysis pipeline.
# =============================================================================

cat("\n=============================================================================\n")
cat("VERIFYING APPENDIX TABLES\n")
cat("=============================================================================\n\n")

# Define the data directory
data_dir <- "Election Myths Stories/data/"

# Define all tables that SHOULD be generated by R code
required_tables <- list(

  # Balance and Randomization Checks (from balance_and_checks.R)
  balance = c(
    "attention_check_summary.tex",
    "attention_check_summary.csv",
    "attention_check_by_treatment.csv",
    "balance_wald_table.tex",
    "balance_wald_test.csv",
    "balance_tests_table.tex",
    "balance_tests_individual.csv",
    "attrition_tests_table.tex",
    "attrition_tests.csv"
  ),

  # Sensitivity Analysis (from modeling_sensitivity.R)
  sensitivity = c(
    "sensitivity_pooled_table.tex",
    "sensitivity_recontact_table.tex",
    "sensitivity_cisa_table.tex"
  ),

  # Main Model Tables (from modeling.R)
  models = c(
    "pooled_models_table.tex",
    "recontact_pooled_models_table.tex",
    "cisa_models_table.tex",
    "Post_combined_models.tex",
    "Recontact_combined_models.tex"
  ),

  # Summary Statistics (from tables.R)
  summary_stats = c(
    "summary_statistics_all.tex",
    "summary_statistics_age_group.tex",
    "summary_statistics_education_level.tex",
    "summary_statistics_gender.tex",
    "summary_statistics_ideology.tex",
    "summary_statistics_party_identification.tex",
    "summary_statistics_political_interest.tex",
    "summary_statistics_race_ethnicity.tex",
    "summary_statistics_urban_rural.tex",
    "summary_statistics_region.tex"
  ),

  # Cross-wave Summary Statistics (from tables.R)
  cross_wave = c(
    "cross_wave_factor_summary_statistics_age_group.tex",
    "cross_wave_factor_summary_statistics_education_level.tex",
    "cross_wave_factor_summary_statistics_gender.tex",
    "cross_wave_factor_summary_statistics_ideology.tex",
    "cross_wave_factor_summary_statistics_party_identification.tex",
    "cross_wave_factor_summary_statistics_political_interest.tex",
    "cross_wave_factor_summary_statistics_race_ethnicity.tex",
    "cross_wave_factor_summary_statistics_urban_rural.tex"
  )
)

# Check each category
all_tables_exist <- TRUE
missing_tables <- list()

for (category in names(required_tables)) {
  cat(sprintf("\nChecking %s tables:\n", category))
  category_tables <- required_tables[[category]]

  for (table_file in category_tables) {
    table_path <- file.path(data_dir, table_file)
    if (file.exists(table_path)) {
      cat(sprintf("  ✓ %s\n", table_file))
    } else {
      cat(sprintf("  ✗ MISSING: %s\n", table_file))
      all_tables_exist <- FALSE
      missing_tables[[category]] <- c(missing_tables[[category]], table_file)
    }
  }
}

# Summary
cat("\n=============================================================================\n")
if (all_tables_exist) {
  cat("SUCCESS: All required tables exist!\n")
  cat("=============================================================================\n")
} else {
  cat("WARNING: Some tables are missing!\n")
  cat("=============================================================================\n\n")
  cat("Missing tables by category:\n")
  for (category in names(missing_tables)) {
    cat(sprintf("\n%s:\n", category))
    for (table in missing_tables[[category]]) {
      cat(sprintf("  - %s\n", table))
    }
  }
  cat("\nRun the appropriate R scripts to generate these tables:\n")
  cat("  - balance_and_checks.R for balance/attrition tables\n")
  cat("  - modeling_sensitivity.R for sensitivity analysis tables\n")
  cat("  - modeling.R for main model tables\n")
  cat("  - tables.R for summary statistics\n")
}

# Also check for any .tex files in data directory that are NOT in our list
cat("\n=============================================================================\n")
cat("Checking for unexpected .tex files in data directory...\n")
cat("=============================================================================\n\n")

all_tex_files <- list.files(data_dir, pattern = "\\.tex$", full.names = FALSE)
expected_files <- unlist(required_tables)
expected_files <- expected_files[grepl("\\.tex$", expected_files)]

unexpected_files <- setdiff(all_tex_files, expected_files)

if (length(unexpected_files) > 0) {
  cat("Found .tex files not in the required list:\n")
  for (f in unexpected_files) {
    cat(sprintf("  - %s\n", f))
  }
  cat("\nThese files may be:\n")
  cat("  1. Legacy files that should be removed\n")
  cat("  2. Files that should be added to the required_tables list\n")
  cat("  3. Additional analysis files not yet documented\n")
} else {
  cat("No unexpected .tex files found.\n")
}

cat("\n")
